site_name: Understanding Metadata

theme:
  name: material
  logo: assets/closer.png
  font:
    text: Source Sans Pro
nav:
  - Introductory module: 
    - Module Introduction: "introduction/1.0 Module Introduction.md"
    - 1.1 Research Data: "introduction/1.1 Research data.md"
    - 1.2 Research Data Management: "introduction/1.2 Research data management.md"
    - 1.3 FAIR: "introduction/1.3 FAIR.md"
    - 2.1 Introduction to Metadata: "introduction/2.1 Introduction to metadata.md"
    - 2.2 Metadata in the Research Data Lifecycle: "introduction/2.2 Metadata in the research lifecycle.md"
    - 2.3 Using Metadata: "introduction/2.3 Using metadata - discover data.md"
    - 2.4 Controlled Vocabularies: "introduction/2.4 Controlled vocabularies.md"
    - 2.5 Metadata Standards: "introduction/2.5 Metadata standards.md"
    - 2.6 Creating Metadata: "introduction/2.6 Creating metadata, study level.md"
    - 2.7 Summary: "introduction/2.7 Introduction summary.md"  
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_css:
  - stylesheets/extra.css
